server:
    port: 3015

spring:
  application:
    name: fuelnet
  datasource:
    url: jdbc:postgresql://postgres:5432/fuelnetdb
    username: fuelnet
    password: fuelnet123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
